Repository SWM-Retriever/Client, pull requests merged in 2022-11, with the labels that each got.

#75 Fix: Enter Group Family ID Bug
  app/src/main/java/org/retriever/dailypet/data/network/signup/FindGroupApiInterface.kt
  app/src/main/java/org/retriever/dailypet/data/repository/signup/FindGroupRepository.kt
  app/src/main/java/org/retriever/dailypet/model/signup/family/EnterFamilyResponse.kt
  app/src/main/java/org/retriever/dailypet/ui/bottomsheet/AddProfileBottomSheet.kt
  app/src/main/java/org/retriever/dailypet/ui/mypage/MyPageMainFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/CreationCompleteFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/viewmodel/FindGroupViewModel.kt
Labels: bug

#77 [PR] Pre-Signed URL && Contribution API && Custom Count
  app/src/main/java/org/retriever/dailypet/data/network/home/HomeApiService.kt
  app/src/main/java/org/retriever/dailypet/data/network/home/StatisticsApiService.kt
  app/src/main/java/org/retriever/dailypet/data/network/signup/PetApiService.kt
  app/src/main/java/org/retriever/dailypet/data/repository/home/HomeRepository.kt
  app/src/main/java/org/retriever/dailypet/model/main/MyContributionResponse.kt
  app/src/main/java/org/retriever/dailypet/model/signup/pet/PetInfo.kt
  app/src/main/java/org/retriever/dailypet/ui/home/care/AddCareFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/home/care/HomeMainFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/home/care/HomeViewModel.kt
  app/src/main/java/org/retriever/dailypet/ui/home/care/ModifyCareFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/CreatePetFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/CreateProfileFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/viewmodel/PetViewModel.kt
  app/src/main/res/layout/fragment_add_care.xml
  app/src/main/res/layout/fragment_modify_care.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature, UI

#83 [PR] Build Variants && Proguard-rules
  app/build.gradle
  app/proguard-rules.pro
Labels: feature

#84 fix : bug
  app/src/main/java/org/retriever/dailypet/model/signup/group/FindGroupResponse.kt
  app/src/main/java/org/retriever/dailypet/ui/mypage/MyPageMainFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/mypage/adapter/GroupAdapter.kt
  app/src/main/java/org/retriever/dailypet/ui/mypage/adapter/PetAdapter.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/adapter/FindGroupAdapter.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/findgroup/AddProfileBottomSheet.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/findgroup/FindGroupFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/pet/BreedAdapter.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/pet/BreedBottomSheet.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/pet/CreatePetFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/pet/PetViewModel.kt
  app/src/main/res/drawable/refresh.xml
  app/src/main/res/layout/fragment_home_main.xml
Labels: feature, UI

#85 [PR] Release 1.2 Fix
  app/build.gradle
  app/src/main/java/org/retriever/dailypet/ui/mypage/adapter/PetAdapter.kt
  app/src/main/java/org/retriever/dailypet/ui/mypage/detail/MyPageDetailFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/CreationCompleteFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/group/CreateGroupFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/group/GroupEntranceFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/group/SelectGroupTypeFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/pet/CreatePetFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/profile/CreateProfileFragment.kt
  app/src/main/res/drawable-hdpi/default_pet_image.png
  app/src/main/res/drawable-mdpi/default_pet_image.png
  app/src/main/res/drawable-xhdpi/default_pet_image.png
  app/src/main/res/drawable-xxhdpi/default_pet_image.png
  app/src/main/res/drawable-xxxhdpi/default_pet_image.png
  app/src/main/res/layout/fragment_create_family.xml
  app/src/main/res/layout/fragment_create_pet.xml
  app/src/main/res/layout/fragment_create_profile.xml
  app/src/main/res/layout/fragment_creation_complete.xml
  app/src/main/res/layout/fragment_family_entrance.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_my_page_detail.xml
  app/src/main/res/layout/fragment_select_family_type.xml
  app/src/main/res/values/strings.xml
Labels: bug, feature, UI

#87 [PR] Release 1.3 Fix
  app/src/main/java/org/retriever/dailypet/ui/home/care/CareFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/home/care/HomeMainFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/home/care/HomeViewModel.kt
  app/src/main/java/org/retriever/dailypet/ui/home/care/ModifyCareFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/login/LoginFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/mypage/MyPageFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/mypage/MyPageMainFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/CreationCompleteFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/signup/pet/CreatePetFragment.kt
  app/src/main/res/drawable-hdpi/rank.png
  app/src/main/res/drawable-mdpi/rank.png
  app/src/main/res/drawable-xhdpi/rank.png
  app/src/main/res/drawable-xxhdpi/rank.png
  app/src/main/res/drawable-xxxhdpi/rank.png
  app/src/main/res/layout/fragment_create_family.xml
  app/src/main/res/layout/fragment_create_pet.xml
  app/src/main/res/layout/fragment_create_profile.xml
  app/src/main/res/layout/fragment_creation_complete.xml
  app/src/main/res/layout/fragment_family_entrance.xml
  app/src/main/res/layout/fragment_home_main.xml
  app/src/main/res/layout/fragment_select_family_type.xml
  app/src/main/res/navigation/login_navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: bug, UI

#89 [PR] Release 1.4 Fix
  app/src/main/java/org/retriever/dailypet/ui/home/care/HomeMainFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/login/LoginActivity.kt
  app/src/main/java/org/retriever/dailypet/ui/login/LoginFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/splash/SplashActivity.kt
  app/src/main/res/layout/fragment_my_page_main.xml
  app/src/main/res/values/strings.xml
Labels: bug, UI

#92 [PR] Release 1.0.1
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/java/org/retriever/dailypet/ui/splash/SplashActivity.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/barchart_marker_view.xml
  app/src/main/res/layout/bottom_sheet_add_profile.xml
  app/src/main/res/layout/bottom_sheet_breed.xml
  app/src/main/res/layout/bottom_sheet_camera.xml
  app/src/main/res/layout/bottom_sheet_group.xml
  app/src/main/res/layout/dialog_search_breed.xml
  app/src/main/res/layout/fragment_add_care.xml
  app/src/main/res/layout/fragment_care.xml
  app/src/main/res/layout/fragment_create_family.xml
  app/src/main/res/layout/fragment_create_pet.xml
  app/src/main/res/layout/fragment_create_profile.xml
  app/src/main/res/layout/fragment_creation_complete.xml
  app/src/main/res/layout/fragment_detail_statistics.xml
  app/src/main/res/layout/fragment_diary_detail.xml
  app/src/main/res/layout/fragment_diary_register.xml
  app/src/main/res/layout/fragment_family_entrance.xml
  app/src/main/res/layout/fragment_find_group.xml
  app/src/main/res/layout/fragment_home_main.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_modify_care.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_page_detail.xml
  app/src/main/res/layout/fragment_my_page_main.xml
  app/src/main/res/layout/fragment_my_page_pet.xml
  app/src/main/res/layout/fragment_my_page_pet_detail.xml
  app/src/main/res/layout/fragment_select_family_type.xml
  app/src/main/res/layout/fragment_statistics.xml
  app/src/main/res/layout/fragment_term_of_service.xml
  app/src/main/res/layout/item_breed.xml
  app/src/main/res/layout/item_date.xml
  app/src/main/res/layout/item_detail_statistics_title.xml
  app/src/main/res/layout/item_diary.xml
  app/src/main/res/layout/item_drop_down.xml
  app/src/main/res/layout/item_my_page_detail.xml
  app/src/main/res/layout/item_not_recent_diary.xml
  app/src/main/res/layout/item_pet.xml
  app/src/main/res/layout/item_profile.xml
  app/src/main/res/layout/item_recent_diary.xml
  app/src/main/res/layout/item_selected_statistics.xml
  app/src/main/res/layout/item_unselected_statistics.xml
  app/src/main/res/layout/layout_empty_diary.xml
  app/src/main/res/values/strings.xml
Labels: bug, feature

#95 [PR] Release 1.0.4
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/retriever/dailypet/ui/home/care/HomeMainFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/mypage/MyPageMainFragment.kt
  app/src/main/java/org/retriever/dailypet/ui/mypage/adapter/ProfileModifyBottomSheet.kt
  app/src/main/java/org/retriever/dailypet/ui/mypage/detail/PetModifyFragment.kt
Labels: bug, feature

#96 [PR] Release 1.0.5
  app/build.gradle
  app/src/main/java/org/retriever/dailypet/ui/mypage/MyPageMainFragment.kt
Labels: bug
